# Generated by Django 5.0 on 2024-01-02 00:03

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of category', max_length=50, unique=True, verbose_name='category')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='color code', max_length=50, verbose_name='color code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'color code',
                'verbose_name_plural': 'color codes',
            },
        ),
        migrations.CreateModel(
            name='ProductClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='class')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'product class',
                'verbose_name_plural': 'product classes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of product [max 60 characters]', max_length=60, verbose_name='name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='description of product', null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.ProductModel.dynamic_directory)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='original price of product. at most 2 decimals. f.e: 1234,56', max_digits=100, null=True, verbose_name='price')),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='discount percentage of product. [1-100]', verbose_name='discount')),
                ('real_price', models.DecimalField(blank=True, decimal_places=2, help_text='price of product after discount', max_digits=100, null=True, verbose_name='real price')),
                ('delivery_duration', models.DurationField(blank=True, help_text='how long will it take to deliver', null=True, verbose_name='delivery duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('class_of_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productclassmodel')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.colormodel')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.sizemodel', verbose_name='size')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='shop.productmodel', verbose_name='cart item')),
            ],
            options={
                'verbose_name': 'cart item',
                'verbose_name_plural': 'cart items',
            },
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='type of product', max_length=60, unique=True, verbose_name='type')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('category', models.ForeignKey(help_text='category', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='shop.categorymodel', verbose_name='category of type')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'type',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='productclassmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='shop.typemodel'),
        ),
    ]
