# Generated by Django 5.0 on 2024-01-07 11:32

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of category', max_length=50, unique=True, verbose_name='category')),
                ('short_description', models.CharField(blank=True, help_text='short description of category', max_length=100, verbose_name='short description')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'product_category',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='class')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'db_table': 'product_class',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizes',
                'db_table': 'product_size',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of product [max 100 characters]', max_length=100, verbose_name='name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='description of product', null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.ProductModel.dynamic_directory)),
                ('sale', models.BooleanField(default=False, help_text='is the product on sale', verbose_name='sale')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='original price of product. at most 2 decimals. f.e: 1234,56', max_digits=100, null=True, verbose_name='price')),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='discount percentage of product. [1-100]', verbose_name='discount')),
                ('real_price', models.DecimalField(blank=True, decimal_places=2, help_text='price of product after discount', max_digits=100, null=True, verbose_name='real price')),
                ('delivery_duration', models.DurationField(blank=True, help_text='how long will it take to deliver', null=True, verbose_name='delivery duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('class_of_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productclassmodel')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='type of product', max_length=60, verbose_name='type')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('category', models.ForeignKey(help_text='category', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='shop.categorymodel', verbose_name='category of type')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'type',
                'db_table': 'product_type',
                'ordering': ('-created_at',),
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='productclassmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='shop.producttypemodel'),
        ),
        migrations.CreateModel(
            name='ProductVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='color code', max_length=50, verbose_name='color code')),
                ('image', models.ImageField(blank=True, null=True, upload_to='color/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='shop.productmodel')),
                ('sizes', models.ManyToManyField(to='shop.productsizemodel')),
            ],
            options={
                'verbose_name': 'variation',
                'verbose_name_plural': 'variations',
                'db_table': 'product_variations',
            },
        ),
    ]
