# Generated by Django 5.0 on 2024-01-02 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cartmodel', verbose_name='cart'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='class_of_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productclassmodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='shop.colormodel'),
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='shop.productmodel', verbose_name='cart item'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.sizemodel', verbose_name='size'),
        ),
        migrations.AddField(
            model_name='typemodel',
            name='category',
            field=models.ForeignKey(help_text='category', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='shop.categorymodel', verbose_name='category of type'),
        ),
        migrations.AddField(
            model_name='productclassmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='shop.typemodel'),
        ),
    ]
