# Generated by Django 5.0 on 2024-01-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemodel',
            name='name',
            field=models.CharField(help_text='type of product', max_length=60, verbose_name='type'),
        ),
        migrations.AlterUniqueTogether(
            name='typemodel',
            unique_together={('name', 'category')},
        ),
    ]
