# Generated by Django 5.0 on 2024-01-08 00:32

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(upload_to=shop.models.ProductModel.dynamic_directory),
        ),
        migrations.AlterField(
            model_name='productvariations',
            name='sizes',
            field=models.ManyToManyField(related_name='variations', to='shop.productsizemodel'),
        ),
    ]
