# Generated by Django 5.0 on 2024-01-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_productmodel_size_productmodel_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='original price of product. at most 2 decimals. f.e: 1234,56', max_digits=100, null=True, verbose_name='price'),
        ),
    ]
