# Generated by Django 5.0 on 2024-01-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
                ('status', models.CharField(choices=[('waiting', 'waiting for payment'), ('preparing', 'preparing for delivery'), ('done', 'done')], default='waiting', help_text='status of the order', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'order',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PromoCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='promo code that would give discount for an order', max_length=50, unique=True, verbose_name='promo code')),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='discount issued by the promo code', verbose_name='discount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expire date')),
            ],
            options={
                'verbose_name': 'promo code',
                'verbose_name_plural': 'promo codes',
                'db_table': 'promo_code',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.productmodel')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'db_table': 'order_item',
            },
        ),
    ]
