# Generated by Django 5.0 on 2024-01-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='total price of the order', max_digits=100, null=True, verbose_name='total price')),
                ('real_price', models.DecimalField(blank=True, decimal_places=2, help_text='price of the order with promo-code', max_digits=100, null=True, verbose_name='real price')),
                ('status', models.CharField(choices=[('waiting', 'waiting for payment'), ('preparing', 'preparing for delivery'), ('done', 'done')], default='waiting', help_text='status of the order', max_length=20, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='promo code that would give discount for an order', max_length=50, unique=True, verbose_name='promo code')),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='discount issued by the promo code', verbose_name='discount')),
            ],
            options={
                'verbose_name': 'promo code',
                'verbose_name_plural': 'promo codes',
            },
        ),
    ]
