# Generated by Django 5.0 on 2024-01-08 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='code',
            field=models.CharField(default=1978, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
