# Generated by Django 5.0 on 2024-01-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitemmodel_code_alter_orderitemmodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
