# Generated by Django 5.0 on 2024-01-11 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitemmodel_code_alter_orderitemmodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodemodel',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, help_text='discount issued by the promo code', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount'),
        ),
    ]
