# Generated by Django 5.0 on 2024-01-12 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_ordermodel_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, help_text='discount issued by the promo code', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount'),
        ),
    ]
